name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bugfix'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
  - 'skip-changelog'
autolabeler:
  - label: 'api-change'
    files:
      - '/api/*'
  - label: 'controllers'
    files:
      - '/internal/*'
  - label: 'bugfix'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'enhancement'
    branch:
      - '/enh\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'dependencies'
    branch:
      - '/deps\/.+/'
      - '/renovate\/.+/'
  - label: 'documentation'
    files:
      - '**/*.md'
    branch:
      - '/docs\/.+/'
template: |
  ## Changes
  $CHANGES
