---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-etcd-aenix-io-v1alpha1-etcdcluster
  failurePolicy: Fail
  name: metcdcluster.kb.io
  rules:
  - apiGroups:
    - etcd.aenix.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - etcdclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-etcd-aenix-io-v1alpha1-etcdcluster
  failurePolicy: Fail
  name: vetcdcluster.kb.io
  rules:
  - apiGroups:
    - etcd.aenix.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - etcdclusters
  sideEffects: None
