---
apiVersion: etcd.aenix.io/v1alpha1
kind: EtcdCluster
metadata:
  name: test
  namespace: default
spec:
  replicas: 3
  podTemplate:
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: etcd
        image: "quay.io/coreos/etcd:v3.5.12"
