---
apiVersion: etcd.aenix.io/v1alpha1
kind: EtcdCluster
metadata:
  name: test
spec:
  replicas: 3
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: standard-with-expansion
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 4Gi
