apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd-operator.fullname" . }}-controller-manager-metrics-service
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kubeRbacProxy.service.type }}
  ports:
    - name: https
      port: {{ .Values.kubeRbacProxy.service.port }}
      protocol: TCP
      targetPort: https
  selector:
    {{- include "etcd-operator.selectorLabels" . | nindent 4 }}
