apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "etcd-operator.fullname" . }}-controller-manager-metrics-service
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
