apiVersion: etcd.aenix.io/v1alpha1
kind: EtcdCluster
metadata:
  labels:
    app.kubernetes.io/name: etcdcluster
    app.kubernetes.io/instance: etcdcluster-sample
    app.kubernetes.io/part-of: etcd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: etcd-operator
  name: etcdcluster-sample
spec:
  options: { }
  storage:
    emptyDir:
      sizeLimit: 1Gi
  podTemplate:
    spec:
      containers:
        - name: etcd
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
  podDisruptionBudgetTemplate: { }
