apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd-operator.fullname" . }}
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portMapping.health }}
      targetPort: {{ .Values.service.portMapping.health }}
      protocol: TCP
      name: health
    - port: {{ .Values.service.portMapping.metrics }}
      targetPort: {{ .Values.service.portMapping.metrics }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "etcd-operator.selectorLabels" . | nindent 4 }}
