apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
  name: {{ include "etcd-operator.fullname" . }}-webhook-service
spec:
  type: {{ .Values.etcdOperator.service.type }}
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.etcdOperator.service.port }}
  selector:
    {{- include "etcd-operator.selectorLabels" . | nindent 4 }}
