apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
  name: {{ include "etcd-operator.fullname" . }}-serving-cert
spec:
  dnsNames:
    - {{ include "etcd-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "etcd-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}
  issuerRef:
    kind: Issuer
    name: {{ include "etcd-operator.fullname" . }}-selfsigned-issuer
  secretName: webhook-server-cert
