apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
  name: {{ include "etcd-operator.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
