apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
  name: {{ include "etcd-operator.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "etcd-operator.fullname" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ include "etcd-operator.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace }}
