apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
  name: {{ include "etcd-operator.fullname" . }}-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
