name: Make run tests e2e

on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize

jobs:
  build:
    # Pull request has label 'ok-to-test' or the author is a member of the organization
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test') || contains(fromJSON('["COLLABORATOR", "MEMBER", "OWNER"]'), github.event.pull_request.author_association)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - uses: helm/kind-action@v1.9.0
        with:
          cluster_name: kind
      - run: make test-e2e KIND_CLUSTER_NAME=kind
