name: Make run tests e2e

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - uses: helm/kind-action@v1.9.0
        with:
          cluster_name: kind
      - run: make test-e2e
