name: Make run tests e2e

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: ${{ github.event.label.name == 'ok-to-test' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - uses: helm/kind-action@v1.9.0
        with:
          cluster_name: kind
      - run: make test-e2e
