name: Release Drafter

on:
  workflow_dispatch:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  release-drafter:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6.0.0
        with:
          disable-releaser: github.ref != 'refs/heads/main'
          config-name: release-drafter.yml
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
