name: Upload release assets
on:
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-assets:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.22.2
      - name: Get tag from current run
        run: |
          TAG=${{ github.ref_name }}
          echo "Tag for packaging chart is $TAG"
          echo "RELEASE_TAG=${TAG}" >> $GITHUB_ENV
          echo "RELEASE_TAG_TRIMMED_V=${TAG#v}" >> $GITHUB_ENV
      - run: make build-dist-manifests IMG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${RELEASE_TAG}
      - uses: svenstaro/upload-release-action@v2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/etcd-operator.yaml
          asset_name: etcd-operator.yaml
          tag: ${{ github.ref }}
          overwrite: true
      - uses: svenstaro/upload-release-action@v2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/etcd-operator.crd.yaml
          asset_name: etcd-operator.crd.yaml
          tag: ${{ github.ref }}
          overwrite: true
      - uses: svenstaro/upload-release-action@v2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/etcd-operator.non-crd.yaml
          asset_name: etcd-operator.non-crd.yaml
          tag: ${{ github.ref }}
          overwrite: true
